### ISSUE TITLE
sortmerna script doesn't exists.

### ISSUE THREAD

**Issue by gokaybiz** [bschiffthaler/ngs#1]
https://github.com/bschiffthaler/ngs/blob/f074cfbf73e92bc7e4d9e9bb8ef46767ae886ea6/base/Dockerfile#L97

**Comment by bschiffthaler** [comment]
Hi!

As you may have noticed, I haven't updated this image in a while and for all intents and purposes, I consider it deprecated. If you really rely on this particular build, I'd be happy to fix it, but IMO a more modular solution provides greater flexibility, which is why I created: https://github.com/bschiffthaler/kogia

The idea here is to have many small single-app containers, as opposed to a large behemoth with everything in it. It is much more in the spirit of docker, and allows you much greater flexibility. I could help you to adapt your workflow to that. Let me know.

/B

**Comment by gokaybiz** [comment]
Thank you. Can you help me about using sortmerna 4.2 usage?
I need an example code snippet to do same thing in here as you do years ago with old version of sortmerna
https://youtu.be/1rNEkWSxB5s?t=1958
Well, we doesn't need indexdb anymore, log parameter deprecated, and also we doesn't have to merge unpaired reads.
Thanks for your support.

**Comment by bschiffthaler** [comment]
I would refer you to the SortMeRNA manual [here](https://github.com/biocore/sortmerna/wiki/2.-User-manual-(todo)#Filtering_pairedend_reads) where that is described.

One thing to consider with a workflow involving SortMeRNA is whether you want the reads that match rRNA (aligned) or those that don't (other). In an RNA-Seq experiment as in the video you usually want the >other< file.

/B
